context('Basic tests', () => {
    beforeEach(() => {
      cy.visit('https://dfehhdd9kceo0.cloudfront.net/')
    })
    it('logging in', () => {
        cy.get('input[name= "username"]').type('customer.test')
        cy.get('input[name= "password"]').type('123456')
        cy.get('button').contains('Login').click()
        cy.get('a[href="/configuration"]').contains("Configurações").click()
        cy.get('img[alt="arrow-down"]').click({ multiple: true })
        cy.get('a[href="/quotation-list"]').contains("Meus Pedidos").click()
        cy.contains('Todas')         
        cy.contains('Pendente') 
        cy.contains('Aceito') 
        cy.contains('Ressalva') 
        cy.contains('Cancelado') 
        cy.contains('Entregue') 
        cy.get('button').contains("Pendente").click()
        cy.wait(2000)
        cy.get('button').contains("Aceito").click()
        cy.wait(2000)
        cy.get('button').contains("Ressalva").click()
        cy.wait(2000)
        cy.get('button').contains("Cancelado").click()
        cy.wait(2000)
        cy.get('button').contains("Entregue").click()
        cy.wait(2000)
        
      
      })
})